# Generated by Django 4.0.4 on 2022-07-10 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='part',
        ),
        migrations.AddField(
            model_name='author',
            name='part',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='articles.part'),
            preserve_default=False,
        ),
    ]
