# Generated by Django 4.0.3 on 2022-06-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_rooms', '__first__'),
        ('club', '__first__'),
        ('articles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=63, unique=True)),
                ('nickname', models.CharField(max_length=15, unique=True)),
                ('article_bookmarks', models.ManyToManyField(to='articles.article')),
                ('chatroom_bookmarks', models.ManyToManyField(to='chat_rooms.chatroom')),
                ('club_bookmarks', models.ManyToManyField(to='club.club')),
            ],
        ),
    ]
