# Generated by Django 4.0.3 on 2022-07-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_rooms', '0001_initial'),
        ('club', '0001_initial'),
        ('links', '0001_initial'),
        ('educations', '0001_initial'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=63, unique=True)),
                ('nickname', models.CharField(max_length=15, unique=True)),
                ('fcm_token', models.TextField(blank=True, default='', null=True)),
                ('article_bookmarks', models.ManyToManyField(blank=True, to='articles.article')),
                ('chatroom_bookmarks', models.ManyToManyField(blank=True, to='chat_rooms.chatroom')),
                ('club_bookmarks', models.ManyToManyField(blank=True, to='club.club')),
                ('education_bookmarks', models.ManyToManyField(blank=True, to='educations.education')),
                ('link_bookmarks', models.ManyToManyField(blank=True, to='links.link')),
            ],
        ),
    ]
