# Generated by Django 4.0.3 on 2022-06-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_rooms', '0001_initial'),
        ('articles', '0001_initial'),
        ('club', '0002_club_image'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='article_bookmarks',
            field=models.ManyToManyField(blank=True, to='articles.article'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chatroom_bookmarks',
            field=models.ManyToManyField(blank=True, to='chat_rooms.chatroom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='club_bookmarks',
            field=models.ManyToManyField(blank=True, to='club.club'),
        ),
    ]
