# Generated by Django 4.0.4 on 2022-07-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club_notifications',
            field=models.ManyToManyField(blank=True, related_name='user_club_notifications', to='club.club'),
        ),
    ]
