# Generated by Django 4.0.4 on 2022-07-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0001_initial'),
        ('accounts', '0002_user_club_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education_notifications',
            field=models.ManyToManyField(blank=True, related_name='user_education_notifications', to='educations.education'),
        ),
    ]
