# Generated by Django 4.0.3 on 2022-06-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
