# Generated by Django 4.0.4 on 2022-07-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0001_initial'),
        ('accounts', '0004_alter_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education_bookmarks',
            field=models.ManyToManyField(blank=True, to='educations.education'),
        ),
    ]
