# Generated by Django 4.0.3 on 2022-06-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('개발자', 'Developer'), ('기획자', 'Productmanger'), ('디자이너', 'Designer')], max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='categories',
            field=models.ManyToManyField(to='chat_rooms.category'),
        ),
    ]
