# Generated by Django 4.0.4 on 2022-07-14 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='categories',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='categories',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='chat_rooms.category'),
            preserve_default=False,
        ),
    ]
