# Generated by Django 4.0.4 on 2022-07-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_rooms', '0002_remove_chatroom_categories_chatroom_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='categories',
            new_name='category',
        ),
    ]
