# Generated by Django 4.0.3 on 2022-07-14 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='category',
        ),
        migrations.AddField(
            model_name='link',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='links.category'),
            preserve_default=False,
        ),
    ]
