# Generated by Django 4.0.3 on 2022-07-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_source_tag_remove_link_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='source',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='links.source'),
        ),
    ]
