# Generated by Django 4.0.3 on 2022-06-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(default='', upload_to='club'),
            preserve_default=False,
        ),
    ]
