# Generated by Django 4.0.4 on 2022-07-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sns',
            name='image',
            field=models.ImageField(default='', upload_to='club'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='activity_cost',
            field=models.TextField(),
        ),
    ]
