# Generated by Django 4.0.4 on 2022-07-02 09:55

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_club_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
