# Generated by Django 4.0.4 on 2022-07-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_sns_image_alter_club_activity_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='detail_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
