# Generated by Django 4.0.4 on 2022-07-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_club_club_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_description',
            field=models.TextField(),
        ),
    ]
