# Generated by Django 4.0.3 on 2022-07-07 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('page_type', models.CharField(blank=True, choices=[('club', 'Club'), ('chat_room', 'Chat Room'), ('article', 'Article'), ('profile', 'Profile')], default='', max_length=15)),
                ('page_id', models.PositiveIntegerField(blank=True, default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
