# Generated by Django 4.0.3 on 2022-06-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='page_id',
            field=models.PositiveIntegerField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='page_type',
            field=models.CharField(blank=True, choices=[('club', 'Club'), ('chat_room', 'Chat Room'), ('article', 'Article'), ('profile', 'Profile')], default='', max_length=15),
        ),
    ]
