# Generated by Django 4.0.4 on 2022-07-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='recruitment_fields',
            field=models.ManyToManyField(to='educations.recruitmentfield'),
        ),
    ]
