# Generated by Django 4.0.4 on 2022-07-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0005_alter_education_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['name']},
        ),
    ]
